services:
  postgres:
    image: postgres
    container_name: auth-toolkit-pg
    restart: "no"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: authtoolkit
    ports:
      - 5432:5432
